project_id = "rhanvchqlilmzxmufode"

[functions.send-push-notification]
verify_jwt = false

[functions.competition-automation]
verify_jwt = false

[functions.send-scheduled-emails]
verify_jwt = false
